language: php
php:
  - '7.0'
  - '7.1'
  - '7.3'
  - '7.4'
  - nightly
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - if [ $(php -r 'echo PHP_MAJOR_VERSION;') == "8" ]; then composer install --ignore-platform-reqs; else composer install; fi
script:
  - vendor/bin/phpunit tests --coverage-clover clover.xml --whitelist src
